
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action ExitAction;
	private global::Gtk.Action HelpAction;
	private global::Gtk.Action AboutAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar1;
	private global::Gtk.Notebook notebook1;
	private global::Gtk.VBox vbox2;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Entry entry2;
	private global::Gtk.Button button1;
	private global::Gtk.Button button4;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Label label2;
	private global::Gtk.HBox hbox12;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView textview1;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Button button3;
	private global::Gtk.Button button2;
	private global::Gtk.Label label1;
	private global::Gtk.VBox vbox3;
	private global::Gtk.HBox hbox4;
	private global::Gtk.Label label4;
	private global::Gtk.Entry entry1;
	private global::Gtk.Button button5;
	private global::Gtk.Label label5;
	private global::Gtk.HBox hbox5;
	private global::Gtk.TextView textview2;
	private global::Gtk.RadioButton radiobutton1;
	private global::Gtk.HBox hbox6;
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	private global::Gtk.TextView textview3;
	private global::Gtk.RadioButton radiobutton2;
	private global::Gtk.HBox hbox7;
	private global::Gtk.ScrolledWindow GtkScrolledWindow3;
	private global::Gtk.TextView textview4;
	private global::Gtk.RadioButton radiobutton3;
	private global::Gtk.HBox hbox8;
	private global::Gtk.ScrolledWindow GtkScrolledWindow4;
	private global::Gtk.TextView textview5;
	private global::Gtk.RadioButton radiobutton4;
	private global::Gtk.HBox hbox10;
	private global::Gtk.Image image2;
	private global::Gtk.Image image1;
	private global::Gtk.Button button7;
	private global::Gtk.Image image3;
	private global::Gtk.Button button6;
	private global::Gtk.VBox vbox4;
	private global::Gtk.Label label6;
	private global::Gtk.Label label7;
	private global::Gtk.HBox hbox9;
	private global::Gtk.Button button8;
	private global::Gtk.Button button9;
	private global::Gtk.Label label3;
	private global::Gtk.Statusbar statusbar1;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.ExitAction = new global::Gtk.Action ("ExitAction", global::Mono.Unix.Catalog.GetString ("Exit"), null, null);
		this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
		w1.Add (this.ExitAction, "<Primary><Mod2>x");
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.AboutAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Byzantio - Game");
		this.Icon = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./byzantio.png"));
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(5));
		this.DefaultWidth = 700;
		this.DefaultHeight = 550;
		this.Gravity = ((global::Gdk.Gravity)(5));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='ExitAction' action='ExitAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='AboutAction' action='AboutAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 1;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		this.hbox1.BorderWidth = ((uint)(10));
		// Container child hbox1.Gtk.Box+BoxChild
		this.entry2 = new global::Gtk.Entry ();
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.Text = global::Mono.Unix.Catalog.GetString ("313");
		this.entry2.IsEditable = true;
		this.entry2.WidthChars = 7;
		this.entry2.InvisibleChar = '•';
		this.hbox1.Add (this.entry2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entry2]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.WidthRequest = 70;
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Search");
		this.hbox1.Add (this.button1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button1]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button ();
		this.button4.WidthRequest = 70;
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString ("Start!");
		this.hbox1.Add (this.button4);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button4]));
		w5.PackType = ((global::Gtk.PackType)(1));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox2.Add (this.hbox1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("<span font-size=\"large\">Year</span>");
		this.label2.UseMarkup = true;
		this.label2.Justify = ((global::Gtk.Justification)(2));
		this.hbox3.Add (this.label2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label2]));
		w7.Position = 1;
		this.vbox2.Add (this.hbox3);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox ();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		this.hbox12.BorderWidth = ((uint)(10));
		// Container child hbox12.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview1 = new global::Gtk.TextView ();
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.textview1.WrapMode = ((global::Gtk.WrapMode)(2));
		this.textview1.PixelsAboveLines = 3;
		this.GtkScrolledWindow.Add (this.textview1);
		this.hbox12.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.GtkScrolledWindow]));
		w10.Position = 0;
		this.vbox2.Add (this.hbox12);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox12]));
		w11.Position = 2;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		this.hbox2.BorderWidth = ((uint)(10));
		// Container child hbox2.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button ();
		this.button3.WidthRequest = 85;
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString ("Next");
		this.hbox2.Add (this.button3);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button3]));
		w12.PackType = ((global::Gtk.PackType)(1));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.WidthRequest = 85;
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("Previous");
		this.hbox2.Add (this.button2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button2]));
		w13.PackType = ((global::Gtk.PackType)(1));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox2.Add (this.hbox2);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
		w14.Position = 3;
		w14.Expand = false;
		w14.Fill = false;
		this.notebook1.Add (this.vbox2);
		// Notebook tab
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Study");
		this.notebook1.SetTabLabel (this.vbox2, this.label1);
		this.label1.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		this.hbox4.BorderWidth = ((uint)(80));
		// Container child hbox4.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Με πόσες ερωτήσεις θέλεις να παίξεις?");
		this.hbox4.Add (this.label4);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label4]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.entry1 = new global::Gtk.Entry ();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.Text = global::Mono.Unix.Catalog.GetString ("10");
		this.entry1.IsEditable = true;
		this.entry1.WidthChars = 5;
		this.entry1.InvisibleChar = '•';
		this.hbox4.Add (this.entry1);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.entry1]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button ();
		this.button5.WidthRequest = 52;
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString ("Ok");
		this.hbox4.Add (this.button5);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.button5]));
		w18.Position = 2;
		w18.Expand = false;
		w18.Fill = false;
		w18.Padding = ((uint)(31));
		this.vbox3.Add (this.hbox4);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox4]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Τι από τα παρακάτω έγινε το ?");
		this.vbox3.Add (this.label5);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label5]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		w20.Padding = ((uint)(8));
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		this.hbox5.BorderWidth = ((uint)(10));
		// Container child hbox5.Gtk.Box+BoxChild
		this.textview2 = new global::Gtk.TextView ();
		this.textview2.CanFocus = true;
		this.textview2.Name = "textview2";
		this.textview2.WrapMode = ((global::Gtk.WrapMode)(3));
		this.textview2.PixelsAboveLines = 3;
		this.hbox5.Add (this.textview2);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.textview2]));
		w21.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.radiobutton1 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("1"));
		this.radiobutton1.CanFocus = true;
		this.radiobutton1.Name = "radiobutton1";
		this.radiobutton1.DrawIndicator = true;
		this.radiobutton1.UseUnderline = true;
		this.radiobutton1.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.hbox5.Add (this.radiobutton1);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.radiobutton1]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		this.vbox3.Add (this.hbox5);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox5]));
		w23.Position = 2;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		this.hbox6.BorderWidth = ((uint)(10));
		// Container child hbox6.Gtk.Box+BoxChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.textview3 = new global::Gtk.TextView ();
		this.textview3.HeightRequest = 10;
		this.textview3.CanFocus = true;
		this.textview3.Name = "textview3";
		this.textview3.WrapMode = ((global::Gtk.WrapMode)(3));
		this.textview3.PixelsAboveLines = 3;
		this.GtkScrolledWindow2.Add (this.textview3);
		this.hbox6.Add (this.GtkScrolledWindow2);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.GtkScrolledWindow2]));
		w25.Position = 0;
		// Container child hbox6.Gtk.Box+BoxChild
		this.radiobutton2 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("2"));
		this.radiobutton2.CanFocus = true;
		this.radiobutton2.Name = "radiobutton2";
		this.radiobutton2.DrawIndicator = true;
		this.radiobutton2.UseUnderline = true;
		this.radiobutton2.Group = this.radiobutton1.Group;
		this.hbox6.Add (this.radiobutton2);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.radiobutton2]));
		w26.Position = 1;
		w26.Expand = false;
		w26.Fill = false;
		this.vbox3.Add (this.hbox6);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox6]));
		w27.Position = 3;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		this.hbox7.BorderWidth = ((uint)(10));
		// Container child hbox7.Gtk.Box+BoxChild
		this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
		this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
		this.textview4 = new global::Gtk.TextView ();
		this.textview4.CanFocus = true;
		this.textview4.Name = "textview4";
		this.textview4.WrapMode = ((global::Gtk.WrapMode)(3));
		this.textview4.PixelsAboveLines = 3;
		this.GtkScrolledWindow3.Add (this.textview4);
		this.hbox7.Add (this.GtkScrolledWindow3);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.GtkScrolledWindow3]));
		w29.Position = 0;
		// Container child hbox7.Gtk.Box+BoxChild
		this.radiobutton3 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("3"));
		this.radiobutton3.CanFocus = true;
		this.radiobutton3.Name = "radiobutton3";
		this.radiobutton3.DrawIndicator = true;
		this.radiobutton3.UseUnderline = true;
		this.radiobutton3.Group = this.radiobutton1.Group;
		this.hbox7.Add (this.radiobutton3);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.radiobutton3]));
		w30.Position = 1;
		w30.Expand = false;
		w30.Fill = false;
		this.vbox3.Add (this.hbox7);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox7]));
		w31.Position = 4;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		this.hbox8.BorderWidth = ((uint)(10));
		// Container child hbox8.Gtk.Box+BoxChild
		this.GtkScrolledWindow4 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow4.Name = "GtkScrolledWindow4";
		this.GtkScrolledWindow4.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow4.Gtk.Container+ContainerChild
		this.textview5 = new global::Gtk.TextView ();
		this.textview5.CanFocus = true;
		this.textview5.Name = "textview5";
		this.textview5.WrapMode = ((global::Gtk.WrapMode)(3));
		this.textview5.PixelsAboveLines = 3;
		this.GtkScrolledWindow4.Add (this.textview5);
		this.hbox8.Add (this.GtkScrolledWindow4);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.GtkScrolledWindow4]));
		w33.Position = 0;
		// Container child hbox8.Gtk.Box+BoxChild
		this.radiobutton4 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("4"));
		this.radiobutton4.CanFocus = true;
		this.radiobutton4.Name = "radiobutton4";
		this.radiobutton4.DrawIndicator = true;
		this.radiobutton4.UseUnderline = true;
		this.radiobutton4.Group = this.radiobutton1.Group;
		this.hbox8.Add (this.radiobutton4);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.radiobutton4]));
		w34.Position = 1;
		w34.Expand = false;
		w34.Fill = false;
		this.vbox3.Add (this.hbox8);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox8]));
		w35.Position = 5;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox ();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		this.hbox10.BorderWidth = ((uint)(10));
		// Container child hbox10.Gtk.Box+BoxChild
		this.image2 = new global::Gtk.Image ();
		this.image2.HeightRequest = 30;
		this.image2.Name = "image2";
		this.image2.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./wrong.png"));
		this.hbox10.Add (this.image2);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.image2]));
		w36.Position = 0;
		w36.Expand = false;
		w36.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.image1 = new global::Gtk.Image ();
		this.image1.HeightRequest = 30;
		this.image1.Name = "image1";
		this.image1.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./correct.png"));
		this.hbox10.Add (this.image1);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.image1]));
		w37.Position = 1;
		w37.Expand = false;
		w37.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.button7 = new global::Gtk.Button ();
		this.button7.WidthRequest = 80;
		this.button7.HeightRequest = 30;
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		// Container child button7.Gtk.Container+ContainerChild
		this.image3 = new global::Gtk.Image ();
		this.image3.Name = "image3";
		this.image3.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./next.png"));
		this.button7.Add (this.image3);
		this.button7.Label = null;
		this.hbox10.Add (this.button7);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.button7]));
		w39.PackType = ((global::Gtk.PackType)(1));
		w39.Position = 2;
		w39.Expand = false;
		w39.Fill = false;
		w39.Padding = ((uint)(37));
		// Container child hbox10.Gtk.Box+BoxChild
		this.button6 = new global::Gtk.Button ();
		this.button6.WidthRequest = 80;
		this.button6.HeightRequest = 30;
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString ("Submit");
		this.hbox10.Add (this.button6);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.button6]));
		w40.PackType = ((global::Gtk.PackType)(1));
		w40.Position = 3;
		w40.Expand = false;
		w40.Fill = false;
		w40.Padding = ((uint)(37));
		this.vbox3.Add (this.hbox10);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox10]));
		w41.Position = 6;
		w41.Expand = false;
		w41.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		this.vbox4.BorderWidth = ((uint)(100));
		// Container child vbox4.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.vbox4.Add (this.label6);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label6]));
		w42.Position = 0;
		w42.Expand = false;
		w42.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Θέλεις να ξαναπαίξεις ?");
		this.vbox4.Add (this.label7);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label7]));
		w43.Position = 1;
		w43.Expand = false;
		w43.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Homogeneous = true;
		this.hbox9.Spacing = -250;
		this.hbox9.BorderWidth = ((uint)(30));
		// Container child hbox9.Gtk.Box+BoxChild
		this.button8 = new global::Gtk.Button ();
		this.button8.WidthRequest = 50;
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.button8.Label = global::Mono.Unix.Catalog.GetString ("Ναι");
		this.hbox9.Add (this.button8);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.button8]));
		w44.Position = 0;
		w44.Expand = false;
		w44.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.button9 = new global::Gtk.Button ();
		this.button9.WidthRequest = 50;
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.Label = global::Mono.Unix.Catalog.GetString ("Όχι");
		this.hbox9.Add (this.button9);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.button9]));
		w45.Position = 1;
		w45.Expand = false;
		w45.Fill = false;
		this.vbox4.Add (this.hbox9);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox9]));
		w46.Position = 2;
		w46.Expand = false;
		w46.Fill = false;
		this.vbox3.Add (this.vbox4);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox4]));
		w47.Position = 7;
		w47.Expand = false;
		w47.Fill = false;
		this.notebook1.Add (this.vbox3);
		global::Gtk.Notebook.NotebookChild w48 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox3]));
		w48.Position = 1;
		// Notebook tab
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Play");
		this.notebook1.SetTabLabel (this.vbox3, this.label3);
		this.label3.ShowAll ();
		this.vbox1.Add (this.notebook1);
		global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook1]));
		w49.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		this.vbox1.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
		w50.Position = 2;
		w50.Expand = false;
		w50.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.label5.Hide ();
		this.hbox5.Hide ();
		this.hbox6.Hide ();
		this.hbox7.Hide ();
		this.hbox8.Hide ();
		this.image2.Hide ();
		this.image1.Hide ();
		this.button7.Hide ();
		this.hbox10.Hide ();
		this.vbox4.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.ExitAction.Activated += new global::System.EventHandler (this.onExit);
		this.AboutAction.Activated += new global::System.EventHandler (this.onAbout);
		this.entry2.TextInserted += new global::Gtk.TextInsertedHandler (this.OnSearchClicked);
		this.button1.Clicked += new global::System.EventHandler (this.OnSearchClicked);
		this.button4.Clicked += new global::System.EventHandler (this.onStartClicked);
		this.button2.Clicked += new global::System.EventHandler (this.OnPrevClicked);
		this.button3.Clicked += new global::System.EventHandler (this.OnNextClicked);
		this.button5.Clicked += new global::System.EventHandler (this.OnSubmitClicked);
		this.button6.Clicked += new global::System.EventHandler (this.OnAnswerButtonClicked);
		this.button7.Clicked += new global::System.EventHandler (this.onNextQuestionClicked);
		this.button8.Clicked += new global::System.EventHandler (this.PlayAgainClicked);
		this.button9.Clicked += new global::System.EventHandler (this.onExit);
	}
}
